ADDR = "127.0.0.1"
PORT = "8000"
SCHEME = "http"
ASSETS_PATH = "js/frontend/dist"
OIDC_DISCOVERY_URL = "http://localhost:4011"
OIDC_CLIENT_ID = "micro-url-mock"
OIDC_CLIENT_SECRET = "micro-url-mock-secret"
OIDC_REDIRECT_URL = "http://localhost:8000/api/user/oidc/callback"
